variables:
  CONDASOURCE: "~/miniconda3/etc/profile.d/conda.sh"

jobs:
- job: 'Testing'
  displayName: 'Unit Testing With Programs'
  pool:
    name: qcengine
  timeoutInMinutes: 360
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 3

  steps:
      # Specify to use the python version defined above
#    - task: UsePythonVersion@0
#      inputs:
#        versionSpec: '$(python.version)'
#        architecture: 'x64'
    - script: |
        echo '##vso[task.setvariable variable=WORKER]worker_test$(python.version)'
        echo '##vso[task.setvariable variable=ENVPREFIX]$(Agent.TempDirectory)/testnv'

      # Additional info about the build
    - script: |
        uname -a
        free -m
        df -h
        ulimit -a
      displayName: "Build Info"

    # Setup python environment
    - script: |
        source $(CONDASOURCE)
        # Create test environment for package
        #conda env create -n $WORKER python=$(python.version) -f devtools/conda-envs/psi.yaml
        conda env create -p $ENVPREFIX python=$(python.version) -f devtools/conda-envs/psi.yaml
        #conda activate $WORKER
        conda activate -p $ENVPREFIX
        # Build and install package
        python setup.py develop --no-deps
      displayName: "Conda Env Creation"

    # Display MongoDB, Conda Environment, Python version
    - script: |
        sleep 5
        python -V
        source $(CONDASOURCE)
        conda activate -p $ENVPREFIX
        conda list
        pwd
        ls -la
      displayName: 'Display'

    # Run tests
    - script: |
        source $(CONDASOURCE)
        conda activate -p $ENVPREFIX
        pytest -rsx -v --cov=qcengine/ qcengine/
      displayName: 'pytest'

    # Cleanup
    - script: |
        conda remove -n $WORKER --yes --all -d
      condition: always()
      failOnStderr: False
      displayName: "Conda Env Cleanup"